source:
  type: file
  properties:
    path: "data/input/csv-to-csv"
    pattern: "*.csv"

transformations:
  - type: filter
    properties:
      column: "status"
      condition: "important"
  - type: map
    properties:
      format: "csv"
      columnMapping:
        id: "id"
        name: "name"
        status: "status"

sink:
  type: file
  properties:
    path: "data/output"
    prefix: "processed"
    extension: ".csv"
    includeHeaders: true
