source:
  type: file
  properties:
    path: "data/input/csv-to-parquet"
    pattern: "*.csv"

transformations:
  - type: filter
    properties:
      column: "status"
      condition: "important"
  - type: map
    properties:
      format: "csv"
      columnMapping:
        id: "id"
        project: "project"
        status: "status"
        assignee: "assignee"
        deadline: "deadline"

sink:
  type: file
  properties:
    path: "data/output"
    format: "parquet"
    schema: |
      {
        "type": "record",
        "name": "CsvRecord",
        "namespace": "com.example",
        "fields": [
          {"name": "id", "type": "string"},
          {"name": "project", "type": "string"},
          {"name": "status", "type": "string"},
          {"name": "assignee", "type": "string"},
          {"name": "deadline", "type": "string"}
        ]
      }
