source:
  type: file
  properties:
    path: "data/input"
    pattern: "*.txt" # Only process text files

transformations:
  - type: filter
    properties:
      condition: "important"
  - type: map
    properties:
      prefix: "processed-"
      suffix: "-done"

sink:
  type: file
  properties:
    path: "data/output"
    prefix: "processed"
    extension: ".txt"
